travis:
  secure:
    BINSTAR_TOKEN: j9NYCgetHaKUgz+11SwZ65rR/IvFzmrfQ9RU1bzpihf2PyQOU2MjvyoXYTR/WUubDZxUsDd3CLeoja4VPzCEFeLT/fnVyfZl3Poy7x/slILPGKmaRqAhYPpijQljDCBKLRM5jrubzNAw3dI6iB/RBpem1Mn0lDC2cSdxLhy6ujmmQPyRFsQ4UGo8MRg1os3DxoEqYBxM33PCaXCAOdSCdqXsFq7jxkv2RPNjtxP542S9qbPqPQeqeDtnFvj54q+RrvYIwyEx7qy04i4mt1XrGYdyCPx6hVf2VnkCZORk9ZqipV8joajNaVr/vFk91AjHVCH3VPco+1FbYjHmuNAstGJgn9gG9qJpD0kwYgtKHstDtoBDcK200DoaNTJSyCbxm4Vp2ASfqft+acPbsAEAVjNNB2fALc8uqDb2LWlWyfFcTlD46BAtRZMeRZ5Tf7d0fF4xbkUcZxKewtAaYBnBAnp6RMMaL9+uUNDO3qSduvffE4rkCtOy+rO2qYrt9WIvTFjteoBEV0dyO20KrgF3zHBrjdxfIBfa2c7CCRoF0m8BxidzVwqczRxpRpdAk7B96fJ+6ruIMXF3tMNHF/xVw/FWR90GLkeX2PhLGHzFTIdnjMM0EOw2OTYsKZT1EdIXhB6stDykNKu83I3dSRaGfH4+f7ZgfShsEPX/GHsJicE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
