travis:
  secure:
    BINSTAR_TOKEN: AfS2p/XazjxkxQpAxNc56v86InUCeRBsmSInqeDmBMuY9GvoNHBAxm1Ro5LIFG1YyPaIhIbqQJKT323a6CTNLuloe1hfnI+d2N4kXSuNA/aAMrIgyfQucQDjEtup1y2xl8qKJqlG5xC+jD1tD36xFMBANnb8lVcksdyMZO5xP6D1Q0LzTCaDQEFBu3/xJqdQB3tbZ8G8QJ9LJ4R6xXM2AVM+Nor3TiTBuT1RZdsC2OL1PIrAfyCr111NwW5+YcIcjYdRXzUxVIvngBUl19BjV/7PZQ98dlUxZyYQSppLqLB6FNw13n8OF+tGmTedHEVwF809XmwVJAgeftyt590YrwyNqdKYqFK+2b11P2loKcH/a9zkXdhktAsn/mr5yD3w7Xqxqz6BV3ao8DYUvJi+fI0x6vPmPvHLZrIWOXo2EBRK2Sf+NJ7vnpTCITuev38PHCQvzZMMJxsD/gQ1MnW7G7Kz9Ksd0Xn/l+Q3hhbIMJsgWlsXhXa0UMz2wmB0NvRc+RWCs38z8ZCAMBONtxQHgnBhpwB5JLl/Xorgr07xbHrgxrSFETNRv4y01/lVZC9jjRX9nULyEnnMbDwTxQHu2F70SAhwz7kg1raQEAasFTsnREDZ/0cV+gsKIPXOYkduvfZ4DrdnxjpwnFciFx7VM9M8P5ZmdjsFZsPkxOdk9Mk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
